profiles:
  development:
  production:
    base_url: http://thinkingconcurrently.com
    deploy:
      host: thinkingconcurrently.com
      path: /home/public

intense_debate_acct: c0aacadded8e090de7c7d19f80ab739d
google_analytics: UA-18608025-1
